### ISSUE TITLE
Tarih hatası

### ISSUE THREAD

**Issue by beyzaerdogan24** [ahmetilhn/zelzele.io#15]
Sayfayı yenildiğimde tarih kısmında Türkçe İngilizcenin birbirinin aynısı olmadığını farkettim. Hatayı fixlemeni heyecanla bekliyorum.

**Comment by ahmetilhn** [comment]
Geri bildirim için teşekkür ederim. En kısa sürede ilgileneceğim @beyzaerdogan24
