### ISSUE TITLE
Deprem Detayı Önerisi

### ISSUE THREAD

**Issue by ahmtcn34** [ahmetilhn/zelzele.io#18]
Deprem detayı grafiğindeki noktalara tıklayınca o depremin detayları getirilebilir.

![image](https://user-images.githubusercontent.com/58213956/222472894-804e0089-9a43-4db4-81da-275860b0aa0d.png)

**Comment by ahmetilhn** [comment]
Müsait olduğumda ilgileneceğim. Feedback için teşekkürler @ahmetcanarif

**Comment by ahmetilhn** [comment]
I don't interest this issue because this feature decrease the browser performance. Thanks for feedback
