### ISSUE TITLE
Deprem tarihi için tooltip

### ISSUE THREAD

**Issue by ahmtcn34** [ahmetilhn/zelzele.io#3]
Deprem listesindeki zamanın üzerine gelince depremin olduğu tarihi detaylı bir şekilde gösterilmesi.
![feat](https://user-images.githubusercontent.com/58213956/221691980-cc7c1a60-f909-425e-9135-5e7d714b465f.png)

**Comment by ahmetilhn** [comment]
Takip ettiğim eventlerden böyle bir click veya hover olayı göremediğim için buna gerek olmadığını düşündüm. Emeğin için teşekkürler. @ahmetcanarif
