### ISSUE TITLE
Map idea

### ISSUE THREAD

**Issue by adilaxmdv** [ahmetilhn/zelzele.io#32]
Features . Map can zoom in out with ctrl + mouse wheel.

**Comment by adilaxmdv** [comment]
??

**Comment by adilaxmdv** [comment]
@ahmetilhn

**Comment by ahmetilhn** [comment]
Closed with https://github.com/ahmetilhn/zelzele.io/pull/36 fyi @adilaxmdv

**Comment by adilaxmdv** [comment]
Fyi mean? :D

**Comment by ahmetilhn** [comment]
https://www.techtarget.com/whatis/definition/for-your-information-FYI#:~:text=In%20both%20chat%20acronyms%20and,action%20is%20required%20or%20expected. :)
