### ISSUE TITLE
Filtreleri temizle

### ISSUE THREAD

**Issue by ahmtcn34** [ahmetilhn/zelzele.io#39]
Filtreleme modalında birde filtreleri temizle seçeneği olursa çok iyi olur.  Nasıl geri döneceklerini anlayamayabilirler.
![image](https://github.com/ahmetilhn/zelzele.io/assets/58213956/3d3c3208-6473-4970-ac41-821f011a313e)

**Comment by ahmetilhn** [comment]
Thank your for feedback. I will add this feature.

**Comment by ahmetilhn** [comment]
Feature added. Follow link for see new feature https://zelzele.io/?magnitude=1
